language: php

dist: trusty

php:
  - hhvm-3.12
  - hhvm-3.24
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

install:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpunit
