language: php

dist: trusty

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm-3.12
  - hhvm-3.18
  - hhvm-3.24
  - nightly

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
  include:
    - php: 7.2
      env:
        - DOCS=yes
        - REQUIRE="sami/sami:^4.0"
      script: ./vendor/bin/sami.php --no-interaction update ./tools/sami-config.php
      after_success: skip
    - php: 7.1
      env: REQUIRE="phpmyadmin/motranslator:^3.0"
    - dist: precise
      php: 5.3

sudo: false

install:
  - if [ -n "$REQUIRE" ] ; then composer require "$REQUIRE" ; fi
  - composer install

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpunit --configuration phpunit.xml.dist
