language: php

dist: trusty

php:
  - hhvm-3.12
  - hhvm-3.24

matrix:
  fast_finish: false

install:
  - composer install

cache:
  directories:
    - $HOME/.composer/cache

script:
  - ./vendor/bin/phpunit
