name: Lint php files

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - QA

jobs:
    lint-php:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
            - name: Use php 7.1
              uses: shivammathur/setup-php@v2
              with:
                  php-version: 7.1
                  tools: composer:v2
            - name: Validate composer.json and composer.lock
              run: composer validate
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install
            - name: Lint files
              run: ./vendor/bin/phpcs

